spring.application.name=patient-service
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/healthconnect_patient?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Pardhu@05052006
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
management.endpoints.web.exposure.include=health,info
# spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/healthconnect
